services:
  db:
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 127.0.0.1:5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 127.0.0.1:8089:8080
    command: start-dev
volumes:
  db:
